version: '3.3'

services:
  flask-portal:
    image: tumtics-dev/talent-pool.backend
    build:
      context: ./flask-portal
    env_file:
      - .env
    ports:
      - 80:8080
    command: ["python", "-m", "app.dummy_server"]