version: '3.3'

services:
  talent-pool:
    image: tumtics-dev/talent-pool
    build:
      context: ./app
    env_file:
      - .env
    ports:
      - 80:8080
    command: ["python", "dummy_server.py"]